name: random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - pip:
      - wandb==0.13.10
      - omegaconf==2.3.0
      - pandas==1.5.3
      - scikit-learn==1.2.1
      - matplotlib==3.7.0
      - pillow==9.4.0
      - mlflow==2.1.1
                   